import type { Course, CourseSchedule } from "@/lib/supabase/types";

export const SAMPLE_COURSES: Course[] = [
  { id: "s01", num: "01", title: "Aparatologia Corporal", category: "Body Tech", price_regular_cents: 85000, price_regular_display: "$850", price_discount_cents: 65000, price_discount_display: "$650", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 1, created_at: "", updated_at: "" },
  { id: "s02", num: "02", title: "Aparatologia Facial", category: "Facial Tech", price_regular_cents: 65000, price_regular_display: "$650", price_discount_cents: 50000, price_discount_display: "$500", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 2, created_at: "", updated_at: "" },
  { id: "s03", num: "03", title: "Botox Avanzado", category: "Injectables", price_regular_cents: 140000, price_regular_display: "$1,400", price_discount_cents: 120000, price_discount_display: "$1,200", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: true, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 3, created_at: "", updated_at: "" },
  { id: "s04", num: "04", title: "Botox Basico", category: "Injectables", price_regular_cents: 115000, price_regular_display: "$1,150", price_discount_cents: 95000, price_discount_display: "$950", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: true, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 4, created_at: "", updated_at: "" },
  { id: "s05", num: "05", title: "Dermaplening", category: "Skin Care", price_regular_cents: 35000, price_regular_display: "$350", price_discount_cents: 25000, price_discount_display: "$250", reservation_deposit_cents: 20000, featured: false, description: "", duration: "6 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 5, created_at: "", updated_at: "" },
  { id: "s06", num: "06", title: "EKG Tech+ CPR BLS", category: "Medical", price_regular_cents: 101600, price_regular_display: "$1,016", price_discount_cents: 85000, price_discount_display: "$850", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 6, created_at: "", updated_at: "" },
  { id: "s07", num: "07", title: "Fibroblast", category: "Skin Tightening", price_regular_cents: 115000, price_regular_display: "$1,150", price_discount_cents: 85000, price_discount_display: "$850", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 7, created_at: "", updated_at: "" },
  { id: "s08", num: "08", title: "Fillers Avanzado", category: "Fillers & Volume", price_regular_cents: 125000, price_regular_display: "$1,250", price_discount_cents: 105000, price_discount_display: "$1,050", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: true, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 8, created_at: "", updated_at: "" },
  { id: "s09", num: "09", title: "Fillers Basico", category: "Fillers & Volume", price_regular_cents: 115000, price_regular_display: "$1,150", price_discount_cents: 95000, price_discount_display: "$950", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: true, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 9, created_at: "", updated_at: "" },
  { id: "s10", num: "10", title: "Full Package", category: "Full Package", price_regular_cents: 299500, price_regular_display: "$2,995", price_discount_cents: 249500, price_discount_display: "$2,495", reservation_deposit_cents: 20000, featured: true, description: "Complete Certification Program", duration: "Multiple days", has_inperson: true, has_online: true, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 10, created_at: "", updated_at: "" },
  { id: "s11", num: "11", title: "Hilos de PDO", category: "Lifting", price_regular_cents: 165000, price_regular_display: "$1,650", price_discount_cents: 140000, price_discount_display: "$1,400", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 11, created_at: "", updated_at: "" },
  { id: "s12", num: "12", title: "Hydradermoabración", category: "Skin Care", price_regular_cents: 15000, price_regular_display: "$150", price_discount_cents: 10000, price_discount_display: "$100", reservation_deposit_cents: 20000, featured: false, description: "", duration: "4 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 12, created_at: "", updated_at: "" },
  { id: "s13", num: "13", title: "Linfático", category: "Body", price_regular_cents: 45000, price_regular_display: "$450", price_discount_cents: 35000, price_discount_display: "$350", reservation_deposit_cents: 20000, featured: false, description: "", duration: "6 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 13, created_at: "", updated_at: "" },
  { id: "s14", num: "14", title: "Maderoterapia", category: "Body", price_regular_cents: 45000, price_regular_display: "$450", price_discount_cents: 35000, price_discount_display: "$350", reservation_deposit_cents: 20000, featured: false, description: "", duration: "6 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 14, created_at: "", updated_at: "" },
  { id: "s15", num: "15", title: "Microdermoabrasión", category: "Skin Care", price_regular_cents: 17500, price_regular_display: "$175", price_discount_cents: 12500, price_discount_display: "$125", reservation_deposit_cents: 20000, featured: false, description: "", duration: "4 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 15, created_at: "", updated_at: "" },
  { id: "s16", num: "16", title: "Microneedling", category: "Dermatology", price_regular_cents: 35000, price_regular_display: "$350", price_discount_cents: 25000, price_discount_display: "$250", reservation_deposit_cents: 20000, featured: false, description: "", duration: "5 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 16, created_at: "", updated_at: "" },
  { id: "s17", num: "17", title: "Peeling", category: "Skin Care", price_regular_cents: 65000, price_regular_display: "$650", price_discount_cents: 50000, price_discount_display: "$500", reservation_deposit_cents: 20000, featured: false, description: "", duration: "6 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 17, created_at: "", updated_at: "" },
  { id: "s18", num: "18", title: "Phlebotomy", category: "Medical", price_regular_cents: 115000, price_regular_display: "$1,150", price_discount_cents: 95000, price_discount_display: "$950", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 18, created_at: "", updated_at: "" },
  { id: "s19", num: "19", title: "Plasma PRP", category: "Blood Science", price_regular_cents: 65000, price_regular_display: "$650", price_discount_cents: 55000, price_discount_display: "$550", reservation_deposit_cents: 20000, featured: false, description: "", duration: "7 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 19, created_at: "", updated_at: "" },
  { id: "s20", num: "20", title: "Reflexologia Corporal", category: "Body", price_regular_cents: 80000, price_regular_display: "$800", price_discount_cents: 65000, price_discount_display: "$650", reservation_deposit_cents: 20000, featured: false, description: "", duration: "8 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 20, created_at: "", updated_at: "" },
  { id: "s21", num: "21", title: "Reflexologia Podal y Craneal", category: "Body", price_regular_cents: 60000, price_regular_display: "$600", price_discount_cents: 45000, price_discount_display: "$450", reservation_deposit_cents: 20000, featured: false, description: "", duration: "6 hours", has_inperson: true, has_online: false, inperson_includes: { kit: true, practice_month: true, digital_material: true, certificate: true, medical_director: true }, online_includes: { access_code: true, digital_material: true, practice_month: true, zoom_sessions: true }, ghl_payment_link_inperson: "", ghl_payment_link_online: "", image_url: "", active: true, sort_order: 21, created_at: "", updated_at: "" },
];

export const SAMPLE_SCHEDULE: CourseSchedule[] = [
  { id: "ss1", course_id: null, course_name: "Fillers", date: "2026-02-15", time: "10:00 AM - 5:00 PM", location: "AAME Training Center, Houston TX", instructor: "Strani Mayorga", spots_total: 12, spots_available: 4, status: "filling", price: "$1,150", price_regular_display: "$1,150", price_discount_display: "$950", category: "Fillers & Volume", created_at: "", updated_at: "" },
  { id: "ss2", course_id: null, course_name: "Armonización Facial + Definición de Mandíbula", date: "2026-03-07", time: "10:00 AM - 5:00 PM", location: "AAME Training Center, Houston TX", instructor: "Strani Mayorga", spots_total: 10, spots_available: 7, status: "open", price: "$1,295", price_regular_display: "$1,295", price_discount_display: "$1,095", category: "Injectables", created_at: "", updated_at: "" },
  { id: "ss3", course_id: null, course_name: "Fibroblast + Lunares", date: "2026-03-14", time: "10:00 AM - 5:00 PM", location: "AAME Training Center, Houston TX", instructor: "Strani Mayorga", spots_total: 12, spots_available: 12, status: "open", price: "$850", price_regular_display: "$850", price_discount_display: "$650", category: "Skin Tightening", created_at: "", updated_at: "" },
  { id: "ss4", course_id: null, course_name: "PDNR de Salmón, Exosomas y Carboxiterapia", date: "2026-03-21", time: "10:00 AM - 5:00 PM", location: "AAME Training Center, Houston TX", instructor: "Strani Mayorga", spots_total: 12, spots_available: 10, status: "open", price: "$850", price_regular_display: "$850", price_discount_display: "$650", category: "Skin Care", created_at: "", updated_at: "" },
  { id: "ss5", course_id: null, course_name: "Flebotomía, PRP", date: "2026-03-28", time: "10:00 AM - 5:00 PM", location: "AAME Training Center, Houston TX", instructor: "Strani Mayorga", spots_total: 12, spots_available: 8, status: "open", price: "$1,095", price_regular_display: "$1,095/$650", price_discount_display: "$950/$550", category: "Medical", created_at: "", updated_at: "" },
  { id: "ss6", course_id: null, course_name: "Botox", date: "2026-04-11", time: "10:00 AM - 5:00 PM", location: "AAME Training Center, Houston TX", instructor: "Strani Mayorga", spots_total: 12, spots_available: 12, status: "open", price: "$950", price_regular_display: "$950", price_discount_display: "$755", category: "Injectables", created_at: "", updated_at: "" },
];
